version: "3.5"

services:

  restapi-mock:
    image: trivadis/mock-server:latest
    container_name: restapi-mock
    hostname: restapi-mock
    ports:
      - 28600:8888
    volumes:
      - ./scripts/restapi-mock/api:/api
    restart: unless-stopped

  calc-ball-possession-stats-worker-1:
    image: trivadis/calc-ball-possession-stats:latest
    hostname: calc-ball-possession-stats-worker-1
    container_name: calc-ball-possession-stats-worker-1
    labels:
      com.platys.restapi.title: 'Kafka REST Proxy'
      com.platys.restapi.url: "http://${PUBLIC_IP}:48080"    

    expose:
      - 8080
    ports:
      - "48080:8080"